services:
  kafka:
    image: confluentinc/cp-kafka:7.5.2
    container_name: kafka
    hostname: kafka
    ports:
      - "19092:19092"
      - "9092:9092"
    environment:
      CLUSTER_ID: "85ruVmoyTJmPGGvmQ-MC5g"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:19092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:19092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_LISTENER_NAME_EXTERNAL_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_LISTENER_NAME_EXTERNAL_ADVERTISED_PORT: "19092"
      KAFKA_LISTENER_NAME_PLAINTEXT_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_LISTENER_NAME_PLAINTEXT_ADVERTISED_PORT: "9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    restart: unless-stopped

volumes:
  kafka_data:
